# Generated by Django 3.0.3 on 2020-02-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
